openapi: 3.0.0
info:
  title: Address Book API
  version: '1.0'
  description: Address book
servers:
  - url: 'http://localhost:3100'
paths:
  /addresses:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/address'
              examples: {}
      operationId: get-addresses
      description: List of addresses
      requestBody: {}
    post:
      summary: ''
      operationId: post-addresses
      responses:
        '201':
          description: Created
      description: Create an address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/address'
  '/addresses/{addressId}':
    parameters:
      - type: string
        name: addressId
        in: path
        required: true
        schema:
          type: integer
        description: The Address ID
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/address'
      operationId: 'get-addresses-{addressId}'
      description: Get an address
      requestBody: {}
    put:
      summary: ''
      operationId: 'put-addresses-{addressId}'
      responses:
        '204':
          description: No Content
      description: Update an address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/address'
    delete:
      summary: ''
      operationId: 'delete-addresses-{addressId}'
      responses:
        '204':
          description: No Content
      description: Delete an address
      requestBody: {}
components:
  schemas:
    address:
      title: address
      type: object
      x-examples:
        example-1:
          id: 1
          city: Winnipeg
          province: Manitoba
          postalcode: R4R 4R4
          address1: 123 Nowhere avenue
        example-2:
          id: 2
          city: Brandon
          province: Manitoba
          postalcode: R2R 2R2
          address1: 345 Iamhere street
      properties:
        id:
          type: integer
        city:
          type: string
        province:
          type: string
        postaCode:
          type: string
        address1:
          type: string
  securitySchemes: {}
